### PR TITLE
omer commit

### PR DESCRIPTION
**Pull request by omer21349**
please

### CODE REVIEW

**Comment by Muratbey33** [comment]
congrats !

**Review by omer21349 — COMMENTED** [review]
good

**Review by elvirka7 — CHANGES_REQUESTED** [review]
Please spell your name first letter with Capital Letter

**Review by KseniiaKr — APPROVED** [review]
great

**Review by KseniiaKr — APPROVED** [review]
good

**Comment by elvirka7** [comment]
You are good now

**Review by KseniiaKr — APPROVED** [review]
great

**Review by elvirka7 — APPROVED** [review]

**Pull request merged**
